print("Welcome to the python World!")
name = input("What is your name? ")
name1 = input("What is your favourite color? ")
name2 = input("What is your favourite animal? ")
print(f"Hello, {name}!")
print("Welcome to my world,\n " + name + "!")
print(f"Your favourite color is {name1}!")
print(f"Your favourite animal is {name2}!")
print("Nice to meet you!")
#Group name based on the user input
print("Welcome to the Group name Generator")
color = input("What is your favourite color?\n ")
animal = input("What is your favourite animal?\n ")
print( "Your group name is: " + color + " " + animal)