hour = input("Enter your hours: ")
rate = input("Enter your rate: ")
hour = float(hour)
rate = float(rate)
pay = round(hour * rate, 2)
print(f"Pay: {pay}")
print(f"Pay: {hour * rate}")
newhour = float(hour)
newrate = float(rate)
print(newhour * newrate)